= Swagger (OpenAPI)

== 1 Introduction

https://swagger.io/[Swagger] est une suite d'outils créée autour de la http://OpenAPI[spécification standard OpenAPI]

Cette spécification (au format json ou yaml) permet de décrire très précisément une API REST: routes, paramètres d'entrée et
de sortie, typage, formats d'échange acceptés, etc.

Une API REST qui veut respecter le standard OpenAPI doit simplement exposer une route `/openapi.[json,yaml]` contenant
toutes les informations nécéssaires pour être ensuite consommé par les clients.

L'avantage d'avoir une telle description disponible est de pouvoir utiliser une suite d'outils bien pratique :
https://github.com/OpenAPITools/openapi-generator[génération automatique] de clients, de serveurs, de documentation...

== 2 Intégration JAX-RS

Dans le projet, nous avons généré le fichier `openapi.[json,yaml]` automatiquement à partir des servlet JAX-RS. Pour cela
nous avons utilisé l'artifact maven : `swagger-jaxrs2-servlet-initializer` :

  <dependency>
    <groupId>io.swagger.core.v3</groupId>
    <artifactId>swagger-jaxrs2</artifactId>
    <version>2.0.0</version>
  </dependency>
  <dependency>
    <groupId>io.swagger.core.v3</groupId>
    <artifactId>swagger-jaxrs2-servlet-initializer</artifactId>
    <version>2.0.0</version>
  </dependency>

Pour plus d'information, veuillez vous référer au https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started[github-wiki] qui est très instructif.

Le fichier `openapi.[json,yaml]` est accessible sur `http://<url>:<port>/<context-root>/openapi.[json,yaml]`.

**customisation**

Nous avons customisé la génération du fichier `openapi.[json|yaml]` en implémentant un https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#reader-listeners[ReaderListener] : link:/dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/SwaggerOperationIdModifier.java[SwaggerOperationIdModifier.java].
Celui ci renomme les ID autogénérés des routes pour leur donner des noms plus explicites qui sont ensuite utilisés par le générateur de clients.

== 3 Swagger-ui

Swagger-ui est une interface web qui se branche sur une API REST OpenAPI-compatible et génère une interface permettant de tester les routes facilement. C'est en quelque sorte un explorateur d'API ou une documentation interactive.

Le code de swagger-ui a été embarqué dans de répertoire git sous forme de site web statique : link:/swagger-ui-dist[swagger-ui-dist].

Ce site web est publié sur ibmcloud via le buildback `static-website` (voir le link:/manifest.yaml[manifest]).

== 4 Openapi-generator

https://github.com/OpenAPITools/openapi-generator[OpenAPI-generator] est un outil qui permet de générer du code à partir
d'une description OpenAPI.

Nous l'avons utilisé pour générer un link:/cli[client en ligne de commande] (codé en bash).

Pour régénérer le client (quand l'API change) il faut executer le script link:/scripts/generate-cli.sh[generate-cli.sh].

NOTE: Il faut avoir installé openapi-generator via npm ou https://github.com/OpenAPITools/openapi-generator#1---installation[un autre gestionnaire de paquets].
