resourcePackages:
  - io.github.oliviercailloux.y2018.opendata.resource
# ignore AbstractResource
ignoredRoutes:
  - "/{id}"
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '1.0'
    title: Dauphine Open Data API specification
    description: 'This API exposes data from Université Paris Dauphine'
  servers:
    - url: https://barth-dauphine-open-datas.eu-gb.mybluemix.net
    - url: https://dauphine-open-datas.eu-gb.mybluemix.net
    - url: http://localhost:8080